version: '3.9'
services:
  tyk-portal:
    build:
      context: .
      dockerfile: ./demos/development/portal/Dockerfile
      args:
        GH_USERNAME: ${GH_USERNAME}
        GH_TOKEN: ${GH_TOKEN}

    container_name: tyk-portal

    entrypoint: ./raava -bootstrap -user=${EMAIL} -pass=${PASSWORD} -provider-name "TykPro@localhost" -provider-type "tyk-pro" -provider-data '{"URL":"http://localhost:${PORTAL_PORT}","Secret":"${PORTAL_USER_TOKEN}","OrgID":"${PORTAL_ORG_ID}"}'

    environment:
      - RAAVA_HOST_PORT=${PORTAL_PORT}
      - RAAVA_DATABASE_ENABLELOGS=true
      - RAAVA_BLOG_ENABLE=true
      - RAAVA_SITE_ENABLE=true

    ports:
      - "${PORTAL_MACHINE_PORT}:${PORTAL_PORT}"

    networks:
      - tyk
