version: '3.9'
services:
  tyk-portal:
    build:
      context: .
      dockerfile: ./demos/development/portal/Dockerfile
      args:
        GH_USERNAME: ${GH_USERNAME}
        GH_TOKEN: ${GH_TOKEN}

    container_name: tyk-portal

    environment:
      - PORTAL_EMAIL=${EMAIL}
      - PORTAL_PASSWORD=${PASSWORD}
      - PORTAL_PORT=${PORTAL_PORT}
      - PORTAL_USER_TOKEN=${PORTAL_USER_TOKEN}
      - PORTAL_ORG_ID=${PORTAL_ORG_ID}
      - RAAVA_HOST_PORT=${PORTAL_PORT}
      - RAAVA_DATABASE_ENABLELOGS=true
      - RAAVA_BLOG_ENABLE=true
      - RAAVA_SITE_ENABLE=true

    ports:
      - "${PORTAL_MACHINE_PORT}:${PORTAL_PORT}"

    networks:
      - tyk
