version: '3.9'

services:
  tyk-pump:
    volumes:
    - ./demos/analytics/datadog/confs/pump.conf:/opt/tyk-pump/pump.conf

  datadog:
    image: datadog/dogstatsd:latest
    container_name: datadog

    environment:
     - DD_API_KEY=${DATADOG_API_KEY}
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true

    ports:
    - "8125:8125/udp"

    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

    networks:
    - tyk
