version: '3.3'
services:
  tyk-dashboard:
    build:
      context: .
      dockerfile: ./tyk-dashboard/Dockerfile
    container_name: tyk-dashboard

    environment:
      - TYK_DB_LICENSEKEY=${TYK_LICENSE_KEY}
      - TYK_DB_LISTENPORT=${DASHBOARD_PORT}
      - TYK_DB_APICONFIG_HOST=${GATEWAY_PROTOCOL}://${GATEWAY_HOST}
      - TYK_DB_APICONFIG_PORT=${GATEWAY_PORT}
      - ORG=${ORG}
      - SLUG=${SLUG}
      - EMAIL=${EMAIL}
      - FIRST=${FIRST}
      - LAST=${LAST}
      - PASSWORD=${PASSWORD}

    ports:
    - "${MACHINE_DASHBOARD_PORT}:${DASHBOARD_PORT}"
    - "5000:5000"

    volumes:
    - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf

    networks:
    - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:latest
    container_name: tyk-gateway

    environment:
      - TYK_GW_LISTENPORT=${GATEWAY_PORT}
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=${DASHBOARD_PROTOCOL}://tyk-dashboard:${DASHBOARD_PORT}
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=${DASHBOARD_PROTOCOL}://tyk-dashboard:${DASHBOARD_PORT}

    ports:
    - "${MACHINE_GATEWAY_PORT}:${GATEWAY_PORT}"

    volumes:
    - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf

    networks:
    - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    container_name: tyk-pump

    volumes:
    - ./confs/pump.conf:/opt/tyk-pump/pump.conf

    networks:
    - tyk

  tyk-redis:
    image: redis
    container_name: redis

    ports:
    - "6379:6379"

    networks:
    - tyk

  tyk-mongo:
    image: mongo:3.2
    container_name: mongo

    command: ["mongod", "--smallfiles"]

    ports:
    - "27017:27017"

    networks:
    - tyk

networks:
  tyk:
