version: '3.3'

services:

  simple-api:
    build:
      context: .
      dockerfile: ./simple-api/Dockerfile

    container_name: simple-api

    volumes:
    - ./simple-api/src/index.js:/var/www/index.js
    - ./simple-api/src/package.json:/var/www/package.json
    - ./simple-api/src/package-lock.json:/var/www/package-lock.json

    ports:
      - "3030:3030"

    networks:
    - tyk
