version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    container_name: tyk-dashboard

    environment:
      - TYK_DB_LICENSEKEY=${TYK_LICENSE_KEY}

    ports:
    - "3000:3000"
    - "5000:5000"

    volumes:
    - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf

    networks:
    - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:latest
    container_name: tyk-gateway

    ports:
    - "8080:8080"

    volumes:
    - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf

    networks:
    - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    container_name: tyk-pump

    volumes:
    - ./confs/pump.conf:/opt/tyk-pump/pump.conf

    networks:
    - tyk

  tyk-redis:
    image: redis
    container_name: redis

    ports:
    - "6379:6379"

    networks:
    - tyk

  tyk-mongo:
    image: mongo:3.2
    container_name: mongo

    command: ["mongod", "--smallfiles"]

    ports:
    - "27017:27017"

    networks:
    - tyk

networks:
  tyk:
