version: '3.3'
services:
  tyk-dashboard:

    image: tykio/tyk-dashboard:v3.0.1

    ports:
    - "3000:3000"
    - "5000:5000"

    environment:
      - TYK_DB_LICENSEKEY=${LICENSE_KEY}

    volumes:
    - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf

  tyk-gateway:
    image: tykio/tyk-gateway:v3.0.0

    ports:
    - "8080:8080"

    volumes:
    - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest

    volumes:
    - ./confs/pump.conf:/opt/tyk-pump/pump.conf

  tyk-redis:
    image: redis

    ports:
    - "6379:6379"

  tyk-mongo:

    image: mongo:3.2

    command: ["mongod", "--smallfiles"]

    ports:
    - "27017:27017"
