version: '3.9'
services:
  tyk-dashboard:
    image: tykregistry.azurecr.io/dashboard

    environment:
      - TYK_DB_TYKAPI_HOST=${GATEWAY_PROTOCOL}://tyk-gateway

    deploy:
      resources:
        reservations:
          cpus: '.5'
          memory: 1G
        limits:
          cpus: '.5'
          memory: 1G

  tyk-gateway:
    environment:
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=${DASHBOARD_PROTOCOL}://tyk-dashboard:${DASHBOARD_PORT}
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=${DASHBOARD_PROTOCOL}://tyk-dashboard:${DASHBOARD_PORT}

    deploy:
      resources:
        reservations:
          cpus: '.5'
          memory: 1G
        limits:
          cpus: '.5'
          memory: 1G

  tyk-pump:
    deploy:
      resources:
        reservations:
          cpus: '.5'
          memory: 1G
        limits:
          cpus: '.5'
          memory: 1G

  tyk-redis:
    volumes:
      - redis-data:/data

    deploy:
      resources:
        reservations:
          cpus: '.5'
          memory: 1G
        limits:
          cpus: '.5'
          memory: 1G

  tyk-mongo:
    volumes:
      - mongo-data:/data/db

    deploy:
      resources:
        reservations:
          cpus: '.5'
          memory: 1G
        limits:
          cpus: '.5'
          memory: 1G

volumes:
  redis-data:
    driver: azure_file
    driver_opts:
      share_name: redis
      storage_account_name: tykacistorage

  mongo-data:
    driver: azure_file
    driver_opts:
      share_name: mongo
      storage_account_name: tykacistorage
