version: '3.9'

services:
  hmac-upstream:
    build:
      context: .
      dockerfile: ./integrations/security/hmac-upstream/Dockerfile

    container_name: hmac-upstream

    volumes:
      - ./integrations/security/hmac-upstream/src/index.js:/var/www/index.js
      - ./integrations/security/hmac-upstream/src/package.json:/var/www/package.json
      - ./integrations/security/hmac-upstream/src/package-lock.json:/var/www/package-lock.json

    ports:
      - "3030:3030"

    networks:
      - tyk
