version: '3.9'

services:
  tyk-pump:
    environment:
      - TYK_PMP_PUMPS_DOGSTATSD_TYPE=dogstatsd
      - TYK_PMP_PUMPS_DOGSTATSD_META_NAMESPACE=pump
      - TYK_PMP_PUMPS_DOGSTATSD_META_ADDRESS=datadog:8125
      - TYK_PMP_PUMPS_DOGSTATSD_META_ASYNCUDS=true
      - TYK_PMP_PUMPS_DOGSTATSD_META_ASYNCUDSWRITETIMEOUT=2
      - TYK_PMP_PUMPS_DOGSTATSD_META_BUFFERED=true
      - TYK_PMP_PUMPS_DOGSTATSD_META_BUFFEREDMAXMESSAGES=32

  datadog:
    image: datadog/dogstatsd:latest
    container_name: datadog

    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true

    ports:
      - "8125:8125/udp"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

    networks:
      - tyk
