version: '3.9'

services:
  express-js:
    build:
      context: .
      dockerfile: ./integrations/services/express-js/Dockerfile

    container_name: express-js

    ports:
      - "3030:3030"

    networks:
      - tyk
