version: '3.3'

services:

  express-js:
    build:
      context: .
      dockerfile: ./backend-servers/express-js/Dockerfile

    container_name: express-js

    volumes:
    - ./backend-servers/express-js/src/index.js:/var/www/index.js
    - ./backend-servers/express-js/src/package.json:/var/www/package.json
    - ./backend-servers/express-js/src/package-lock.json:/var/www/package-lock.json

    ports:
      - "3030:3030"

    networks:
    - tyk
